### ISSUE TITLE
No module named 'sample_utils'

### ISSUE THREAD

**Issue by logesh-works** [whitphx/streamlit-webrtc#1569]
Traceback (most recent call last):
  File "C:\Users\LOGI\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\LOGI\AppData\Local\Temp\tmpa2jubgh0\app.py", line 17, in <module>
    from sample_utils.download import download_file
ModuleNotFoundError: No module named 'sample_utils'

**Comment by yaleimeng** [comment]
visit  https://github.com/whitphx/streamlit-webrtc-example  and git clone or download zip file.
Then, you can find  'sample_utils' folder.
