### ISSUE TITLE
🐞 : `NotImplementedError: transform() is not implemented`

### ISSUE THREAD

**Issue by joe733** [whitphx/streamlit-webrtc#215]
Hi, first of thanks a lot for this module, really appreciate your hard work. I'm trying to reproduce the simple example given in your [write up](https://dev.to/whitphx/build-a-web-based-real-time-computer-vision-app-with-streamlit-57l2?signin=true). Here's the code:

```python
import cv2 as cv
from streamlit_webrtc import VideoTransformerBase, webrtc_streamer


class VideoTransformer(VideoTransformerBase):

    def capture(self, frame):
        img = frame.to_ndarray(format='bgr24')
        img = cv.cvtColor(cv.Canny(img, 100, 200), cv.COLOR_GRAY2BGR)
        return img


webrtc_streamer(key='Test', video_transformer_factory=VideoTransformer)
```

But I see no change:

![image](https://user-images.githubusercontent.com/38415384/119352321-29bd9d80-bcbf-11eb-8fe0-2d7503758584.png)

However there's an error:

```python
...
2021-05-24 18:42:11.462 Connection(0) ICE completed
2021-05-24 18:42:11.463 ICE connection state is completed
2021-05-24 18:42:11.565 transform() is deprecated. Implement recv() instead.
2021-05-24 18:42:11.565 Error occurred in the WebRTC thread:
2021-05-24 18:42:11.566 Traceback (most recent call last):
2021-05-24 18:42:11.566   File "/home/jovial/Dev/anaconda3/envs/vdk/lib/python3.8/site-packages/streamlit_webrtc/process.py", line 157, in _run_worker_thread
2021-05-24 18:42:11.566     self._worker_thread()
2021-05-24 18:42:11.566   File "/home/jovial/Dev/anaconda3/envs/vdk/lib/python3.8/site-packages/streamlit_webrtc/process.py", line 242, in _worker_thread
2021-05-24 18:42:11.566     new_frames = finished.result()
2021-05-24 18:42:11.566   File "/home/jovial/Dev/anaconda3/envs/vdk/lib/python3.8/site-packages/streamlit_webrtc/process.py", line 54, in recv_queued
2021-05-24 18:42:11.566     return [self.recv(frames[-1])]
2021-05-24 18:42:11.566   File "/home/jovial/Dev/anaconda3/envs/vdk/lib/python3.8/site-packages/streamlit_webrtc/process.py", line 45, in recv
2021-05-24 18:42:11.566     new_image = self.transform(frame)
2021-05-24 18:42:11.566   File "/home/jovial/Dev/anaconda3/envs/vdk/lib/python3.8/site-packages/streamlit_webrtc/process.py", line 33, in transform
2021-05-24 18:42:11.567     raise NotImplementedError("transform() is not implemented.")
2021-05-24 18:42:11.567 NotImplementedError: transform() is not implemented.
...
```

Am I doing something wrong?

**Comment by joe733** [comment]
Oh I see! My bad 🤦🏻‍♂️ The `transform` function needs to be implemented. Sorry to bother you! Closing.
