### ISSUE TITLE
Video is not being displayed

### ISSUE THREAD

**Issue by Ashish013** [whitphx/streamlit-webrtc#44]
Hey @whitphx, I've tracked this repo from the forums. And when I'm trying to access [the website](https://share.streamlit.io/whitphx/streamlit-webrtc-example/main/app.py) for a project I'm working on, it is taking forever to display even the simple video loopback. So is this a problem from myside or is the site broken ?

![Screenshot (269)](https://user-images.githubusercontent.com/56002521/106797721-007ef000-6683-11eb-9e55-3382136d47b3.png)

**Comment by whitphx** [comment]
Hi, thank you for reporting.
I conformed the problem occurred, but in my case, it was finally successful after trying several times reloading the page and clicking the start button.
Probably it was because the VM instance of Streamlit Sharing is not powerful enough to launch the server-side WebRTC process quickly and it causes connection timeout. Another possibility is that the network interface of the VM instance has some limitations such as blocking some ports, but I can't see the managed backend like that anyway.

However, there are many other potential obstacles to establish WebRTC connection to remote peers.
If the sample app still does not work in your case, please try the following things to identify the cause.
* Run the example on your local environment, following the [README](https://github.com/whitphx/streamlit-webrtc#example-).
  * Connecting from localhost to localhost is the easiest way to succeed. If it is successful while the cloud-base demo fails, there are some problems on the network between your local environment to the remote host (Streamlit Sharing server). For example, inside a office network, the FW can be configured to drop some packets.
  * FYI: Using relay servers, called TURN server, can solve this problem as Google Meet or Zoom may do, but this sample app does not now because it takes cost.
* Try this page: https://streamlit-webrtc-example.herokuapp.com/ , which is the same app hosted on a different host, Heroku. If it is successful, the problem possibly resides in Streamlit Sharing.
* If all above failed, check the log printed on the console of your web browser and send it to me. Some error might have occurred on the client-side.

**Comment by Ashish013** [comment]
Hey @whitphx, thanks a lot for getting back so fast. I've tried running the example locally and it works like a charm 💯 .
 Kudos to you, ❤️ the work you're doing for the community.

I've  also tried the app hosted on heroku and the outcome is the same as the app hosted on streamlit. Looking forward to complete web-rtc through streamlit without any hiccups.

**Comment by whitphx** [comment]
Thank you the report!
I will check it.

**Comment by superwhyun** [comment]
Thank you for your great work!
In my case, when I tried object detection after launching streamlit server, it works well. But, when I stop the streaming and start again, it stucked.

**Comment by superwhyun** [comment]
I found a solution.

in the app.py:321, 

<Before>
            if webrtc_ctx.video_transformer:
                while True:
                    result = webrtc_ctx.video_transformer.result_queue.get()
                    labels_placeholder.table(result)

<After>
            while True:
                if webrtc_ctx.video_transformer:    
                    result = webrtc_ctx.video_transformer.result_queue.get()
                    labels_placeholder.table(result)
                else:
                    break

This needs to be reflected to the example codes accordingly.
Thanks.

**Comment by whitphx** [comment]
Thank you for the report!

While this problem may be related to #73 and I'm working on it,
your workaround looks nice to avoid the problem with the current version! Thank you and I will reflect it to the sample app.

**Comment by Usama3059** [comment]
@Ashish013  same problem does you find  any solution

**Comment by whitphx** [comment]
The problem has still been happening sometimes and I updated the fix suggested in https://github.com/whitphx/streamlit-webrtc/issues/44#issuecomment-796563540 .

Timeout must be set to `queue.get()` to avoid being stuck forever.

```python
result = webrtc_ctx.video_transformer.result_queue.get(timeout=1.0)
``` 

I updated `app.py` in #120

**Comment by hoodlord89** [comment]
@whitphx  any times I try to run the app.py I receive “Your app is having trouble loading the streamlit_webrtc.webrtc_streamer component”.how can I solve this issue

**Comment by dinisusmc** [comment]
I've built my app and run it successfully on local host. When trying to deploy to streamlit share I get a libgl1 import error in the logs. These files need to be installed with apt on linux so I cant incorporate them into my requirements file. How can I incorporate that dependency when deploying?

**Comment by AIOnGraph** [comment]
Exception in callback Transaction.__retry()

handle: <TimerHandle when=3215181.568628646 Transaction.__retry()>

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1054, in sendto

    self._sock.sendto(data, addr)

AttributeError: 'NoneType' object has no attribute 'sendto'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run

    self._context.run(self._callback, *self._args)

  File "/home/adminuser/venv/lib/python3.9/site-packages/aioice/stun.py", line 312, in __retry

    self.__protocol.send_stun(self.__request, self.__addr)

  File "/home/adminuser/venv/lib/python3.9/site-packages/aioice/ice.py", line 266, in send_stun

    self.transport.sendto(bytes(message), addr)

  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1064, in sendto

    self._fatal_error(

  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 711, in _fatal_error

    self._loop.call_exception_handler({

AttributeError: 'NoneType' object has no attribute 'call_exception_handler'

Exception in callback Transaction.__retry()

handle: <TimerHandle when=3215243.142471571 Transaction.__retry()>

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1054, in sendto

    self._sock.sendto(data, addr)

AttributeError: 'NoneType' object has no attribute 'sendto'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run

    self._context.run(self._callback, *self._args)

  File "/home/adminuser/venv/lib/python3.9/site-packages/aioice/stun.py", line 312, in __retry

    self.__protocol.send_stun(self.__request, self.__addr)

  File "/home/adminuser/venv/lib/python3.9/site-packages/aioice/ice.py", line 266, in send_stun

    self.transport.sendto(bytes(message), addr)

  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1064, in sendto

    self._fatal_error(

  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 711, in _fatal_error

    self._loop.call_exception_handler({

AttributeError: 'NoneType' object has no attribute 'call_exception_handler'


This error comes when i deploy my app on streamlit. the webcam not started and give me this error.
here is my webcam code 
if option == "📷 Webcam":
        st.sidebar.write("Using Webcam")
        try:
            print(000000000000000000000000000000000000000000000000000000000000000)
            webrtc_ctx = webrtc_streamer(
                key="example",
                video_processor_factory=lambda: processor,
                mode=WebRtcMode.SENDRECV,
                media_stream_constraints={"video": True, "audio": False},
                rtc_configuration=rtc_configuration,
                async_processing=True,
                # video_frame_callback=processor.recv
            )
            print(webrtc_ctx,55555555555555555555555555555555555555555555555)
        except Exception as e:
            st.error(f"An error occurred: {e}")
        if webrtc_ctx and webrtc_ctx.video_processor:
            webrtc_ctx.video_processor.confidence_threshold = confidence_threshold
            webrtc_ctx.video_processor.nms_threshold = nms_threshold
            print(webrtc_ctx.video_processor,4444444444444444444444444444444444444444444444444444444444)
            
            fix this issue if someone solve this.
