### ISSUE TITLE
'NoneType' object has no attribute 'call_exception_handler'

### ISSUE THREAD

**Issue by Dreaming-future** [whitphx/streamlit-webrtc#845]
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run

    self._context.run(self._callback, *self._args)

  File "/home/appuser/venv/lib/python3.7/site-packages/aioice/stun.py", line 309, in __retry

    self.__protocol.send_stun(self.__request, self.__addr)

  File "/home/appuser/venv/lib/python3.7/site-packages/aioice/ice.py", line 243, in send_stun

    self.transport.sendto(bytes(message), addr)

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 1011, in sendto

    exc, 'Fatal write error on datagram transport')

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 677, in _fatal_error

    self._loop.call_exception_handler({

AttributeError: 'NoneType' object has no attribute 'call_exception_handler'

2022-05-06 08:28:55.925 Exception in callback Transaction.__retry()

handle: <TimerHandle when=668465.429274496 Transaction.__retry()>

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 1002, in sendto

    self._sock.sendto(data, addr)

AttributeError: 'NoneType' object has no attribute 'sendto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run

    self._context.run(self._callback, *self._args)

  File "/home/appuser/venv/lib/python3.7/site-packages/aioice/stun.py", line 309, in __retry

    self.__protocol.send_stun(self.__request, self.__addr)

  File "/home/appuser/venv/lib/python3.7/site-packages/aioice/ice.py", line 243, in send_stun

    self.transport.sendto(bytes(message), addr)

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 1011, in sendto

    exc, 'Fatal write error on datagram transport')

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 677, in _fatal_error

    self._loop.call_exception_handler({

AttributeError: 'NoneType' object has no attribute 'call_exception_handler'

2022-05-06 08:28:55.945 Exception in callback Transaction.__retry()

handle: <TimerHandle when=668465.45046249 Transaction.__retry()>

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 1002, in sendto

    self._sock.sendto(data, addr)

AttributeError: 'NoneType' object has no attribute 'sendto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run

    self._context.run(self._callback, *self._args)

  File "/home/appuser/venv/lib/python3.7/site-packages/aioice/stun.py", line 309, in __retry

    self.__protocol.send_stun(self.__request, self.__addr)

  File "/home/appuser/venv/lib/python3.7/site-packages/aioice/ice.py", line 243, in send_stun

    self.transport.sendto(bytes(message), addr)

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 1011, in sendto

    exc, 'Fatal write error on datagram transport')

  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 677, in _fatal_error

    self._loop.call_exception_handler({

AttributeError: 'NoneType' object has no attribute 'call_exception_handler'

**Comment by whitphx** [comment]
I can't understand it.

* Write the details
* Format the log to be easy to read

You should read articles like https://wiredcraft.com/blog/how-we-write-our-github-issues/

**Comment by whitphx** [comment]
Dup #552
